# Generated by Django 5.2 on 2025-04-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.CharField(default='Алматы', max_length=100, verbose_name='Город'),
        ),
    ]
