# Generated by Django 5.2 on 2025-04-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0002_car_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(choices=[('Алматы', 'Алматы'), ('Нур-Султан', 'Нур-Султан'), ('Шымкент', 'Шымкент'), ('Караганда', 'Караганда'), ('Актобе', 'Актобе')], default='Алматы', max_length=100, verbose_name='Город'),
        ),
    ]
