# Generated by Django 5.2 on 2025-04-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0003_alter_car_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Свободен'), ('pending', 'В ожидании'), ('confirmed', 'Занят')], default='available', max_length=10, verbose_name='Статус'),
        ),
    ]
